default_install_hook_types:
  - pre-commit
  - post-checkout
  - post-merge
  - post-rewrite

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.10.12
    hooks:
      - id: uv-lock
        # args:
        #   - --upgrade
      - id: uv-export
        files: ^(uv\.lock|requirements\.txt)$
        args:
          - --frozen
          - --no-dev
          - --output-file=requirements.txt
      - id: uv-sync
        always_run: true
        args:
          - --locked
          - --group=dev

  - repo: https://github.com/tsvikas/sync-with-uv
    rev: v0.5.0
    hooks:
      - id: sync-with-uv

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args:
          - --maxkb=500
      - id: check-case-conflict
      - id: check-merge-conflict
        args:
          - --assume-in-merge
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-check-mock-methods
      - id: python-use-type-annotations
      - id: text-unicode-replacement-char

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.20.0
    hooks:
      - id: pyproject-fmt

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade
        args:
          - --py312-plus

  - repo: https://github.com/PyCQA/isort
    rev: 8.0.1
    hooks:
      - id: isort
        args:
          - --settings-path=pyproject.toml

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 26.3.1
    hooks:
      - id: black
        args:
          - --config=pyproject.toml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.7
    hooks:
      - id: ruff-check
        args:
          - --fix
          # - --unsafe-fixes
      - id: ruff-format

  - repo: https://github.com/PyCQA/bandit
    rev: 1.9.4
    hooks:
      - id: bandit
        args:
          - -c
          - pyproject.toml

  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args:
          - --config=.flake8
        additional_dependencies:
          - flake8-2020~=1.8
          - flake8-absolute-import~=1.0
          - flake8-annotations~=3.2
          - flake8-boolean-trap~=1.0
          - flake8-bugbear~=25.11.29
          - flake8-builtins~=3.1
          - flake8-classmethod-staticmethod~=2.1
          - flake8-cognitive-complexity~=0.1
          - flake8-comprehensions~=3.17
          - flake8-datetimez~=20.10
          - flake8-docstrings~=1.7
          - flake8-encodings~=0.5
          - flake8-implicit-str-concat~=0.6
          - flake8-logging~=1.8
          - flake8-no-pep420~=2.9
          - flake8-noqa~=1.5
          - flake8-print~=5.0
          - flake8-pytest-style~=2.2
          - flake8-raise~=0.0.5
          - flake8-return~=1.2
          - flake8-simplify~=0.22
          - flake8-tidy-imports~=4.12
          - flake8-type-checking~=3.0
          - flake8-use-fstring~=1.4
          - flake8-useless-assert~=0.4
          - pep8-naming~=0.15
          - tryceratops~=2.4

  - repo: https://github.com/PyCQA/pylint
    rev: v4.0.5
    hooks:
      - id: pylint
        args:
          - --rcfile=pyproject.toml

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        args:
          - --config-file=pyproject.toml
        additional_dependencies:
          - betterproto~=2.0.0b7
          - notion-client>=2.5
          - pydantic>=2.12
          - python-dotenv~=1.2.2
          - tenacity~=9.1.4
          - types-requests~=2.32
          - ultimate-notion~=0.9.6
