repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        args:
          - --maxkb=500
      - id: check-case-conflict
      - id: check-merge-conflict
        args:
          - --assume-in-merge
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-check-mock-methods
      - id: python-use-type-annotations
      - id: text-unicode-replacement-char

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: 2.2.4
    hooks:
      - id: pyproject-fmt

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
      - id: pyupgrade
        args:
          - --py312-plus

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args:
          - --settings-path=pyproject.toml

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.8.0
    hooks:
      - id: black
        args:
          - --config=pyproject.toml

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        args:
          - -c
          - pyproject.toml

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args:
          - --config=.flake8
        additional_dependencies:
          - flake8-2020~=1.8
          - flake8-boolean-trap~=1.0
          - flake8-bugbear~=24.8.19
          - flake8-builtins~=2.5
          - flake8-comprehensions~=3.15
          - flake8-datetimez~=20.10
          - flake8-docstrings~=1.7
          - flake8-encodings~=0.5
          - flake8-implicit-str-concat~=0.4
          - flake8-logging~=1.6
          - flake8-no-pep420~=2.7
          - flake8-noqa~=1.3
          - flake8-print~=5.0
          - flake8-pytest-style~=1.7
          - flake8-raise~=0.0.5
          - flake8-return~=1.2
          - flake8-simplify~=0.20
          - flake8-tidy-imports~=4.10
          - flake8-type-checking~=2.9
          - flake8-use-fstring~=1.4
          - flake8-useless-assert~=0.4
          - pep8-naming~=0.14
          - tryceratops~=2.4

  - repo: https://github.com/PyCQA/pylint
    rev: v3.3.0
    hooks:
      - id: pylint
        args:
          - --rcfile=pyproject.toml

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        args:
          - --config-file=pyproject.toml
        additional_dependencies:
          - betterproto~=2.0.0b7
          - notion-client>=2.2.1
          - pydantic>=2.8.2
          - python-dotenv~=1.0.1
          - tenacity~=9.0.0
          - types-requests~=2.31

  # - repo: https://github.com/astral-sh/uv-pre-commit
  #   rev: 0.4.15
  #   hooks:
  #     - id: pip-compile
  #       name: pip-compile runtime deps
  #       args:
  #         - pyproject.toml
  #         - --no-emit-package=setuptools
  #         - --no-strip-markers
  #         - --output-file=requirements.txt
  #       files: ^pyproject.toml|requirements.txt$
  #     - id: pip-compile
  #       name: pip-compile development deps
  #       args:
  #         - pyproject.toml
  #         - --no-emit-package=setuptools
  #         - --no-strip-markers
  #         - --extra=dev
  #         - --output-file=dev-requirements.txt
  #       files: ^pyproject.toml|dev-requirements.txt$
