name: "✅ Linter"

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Get source code
        uses: actions/checkout@v7

      - name: Set up uv
        uses: astral-sh/setup-uv@v10.0.1

      - name: Run prek
        uses: j178/prek-action@v3.0.0
        with:
          extra-args: --all-files --verbose
